version: '3'
services:
  fastapi-service:
    build: .
    image: fastapi-service:latest
    command: poetry run uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    ports:
      - "5005:5000"
    volumes:
      - ./src:/app/src
      - ./secrets:/app/secrets
      - ./alembic:/app/alembic
    depends_on:
      - database

  database:
    image: postgres:13.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fastapi_service_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql